#include: "rules/common.smk"

configfile: '../config/config.yaml'

print(config)

##### Target rules #####

import pandas as pd
import os

sample_names = pd.read_csv ( config['Sample_names'] )
pseudo_codes = pd.read_csv ( config['Pseudogenome_codes'])
# Create arrays of the sample names
samples = sample_names['Sample_name'].values
pseudos = pseudo_codes['PSGs'].values
print(samples)


rule all:
    input:
        config['Results']['o1'],
        config['Results']['o2'],
        config['Results']['o3'],
        config['Results']['o4'],
        config['Results']['o5'],
        config['Results']['degs'], # Counts matrix for the DEGs
        config['files_pseudogenomes']['PSG_dict'], # Dictionary of the pseudogenomes
        config['files_pseudogenomes']['PSG_index'], # Index of the pseudogenomes
        config['files_pseudogenomes']['PSG_fai'], # fai index of the pseudogenomes
        #config['error'] # Estimate the error of your SNP call
        #config['Other_intermediate_files']['bam'],
        #config['Other_intermediate_files']['bqsr'],
        #config['Other_intermediate_files']['valid_bqsr'],
        #config['Other_intermediate_files']['valid_bqsr_PSG'],
        #config['Other_intermediate_files']['recal_table']


##### MODULES #####
###################

# Preparation #
###############
ends = config['params']['star']['mode']
if ends == "SE":
    include: "rules/trimmomatic_se.smk"#In the trimming R3 input is called 2 for the output
    include: "rules/star_gi_ref.smk"
    # First SNP callling on the reference genome #
    ##############################################
    include: "rules/star_se_ref.smk"        # map with STAR
else:
    include: "rules/trimmomatic_pe.smk"#In the trimming R3 input is called 2 for the output
    include: "rules/star_gi_ref.smk"
    # First SNP callling on the reference genome #
    ##############################################
    include: "rules/star_pe_ref.smk"        # map with STAR
exit()

include: "rules/replace_rg_ref.smk"     # Replace or add read Groups:
include: "rules/mark_duplicates_ref.smk"# Mark and eliminate Duplicates:
include: "rules/splitNcigar_ref.smk"    # Split Ncigars
inlcude: "rules/validate_bam_ref.smk"   # Validate bam
include: "rules/htseq.smk"              # Make count matrix from each sample for differentially expressed genes
include: "rules/haplotype_caller_ref.smk"# Haplotype caller
include: "rules/combine_gvcfs.smk"      # Combine gvcf
include: "rules/genotype_gvcfs.smk"     # Genotype gvcf
include: "rules/gatk_select.smk"        # Select biallelic sites
include: "rules/gatk_variantstotable.smk" # Make the table


## Pseudogenomes pipeline ##
############################
# From here it starts the part of the pipeline that creates the pseudogenomes
# and prepares the vcf files for the elimination of the mapping bias.

# Subset by keeping positions with GQ >= 30 and DP >=5
# Not keeping indels
include: "rules/subset_ref.smk"         # Subset the genome
include: "rules/pseudogenomes.smk"      # Create the Pseudogenomes

## Second calling of SNPs on the pseudogenomes ##
#################################################


## Now you can start the pipeline again from the fastq file for the pseudogenomes:
if ends == "SE":
    include: "rules/star_se_pseudogenomes.smk"        # map with STAR
else:
    include: "rules/star_pe_pseudogenomes.smk"        # map with STARinclude: "rules/star_pseudogenomes.smk"       # Map against pseudogenomes
exit()

include: "rules/replace_rg_pseudo.smk"        # Replace or add read groups
include: "rules/mark_duplicates_pseudo.smk"    # Mark and eliminate duplicates
include: "rules/splitNcigar_pseudo.smk"       # Split Ncigars
include: "rules/validate_bam_pseudo.smk"      # Validate bam
include: "rules/haplotype_caller_pseudo.smk"  # Haplotype caller
include: "rules/combine_gvcfs_pseudo.smk"     # Combine gvcf
include: "rules/genotype_gvcfs_pseudo.smk"    # Genotype gvcf
include: "rules/select_pseudo.smk"            # Select biallelic variants

## Annotate vcf files ##
########################
# Convert the vcf file to annovar format thus extracting the SNPs
# Make tokens for the annotation script
# Collect the annotations in the db
# Make tokens for the tables with the annotation
# Annotate the file. This file can be used for the creation of the pseudogenomes
include: "rules/annotation.smk"


## Data science ##
##################
## Create the count table for the data wrangling
include: "rules/variants_to_table.smk"  # Make the table
include: "rules/table2df.smk"           # Preapre the tables for the workflow format

# Workflow
include: "rules/workflow.smk"           # Processing the data

# Stats only in non-mae
include: "rules/stats.smk"              # Apply Chi^2, Fisher and Binomial on NO MAE

# Tables and figures for publication
include: "rules/results.smk"
include: "rules/results_mae.smk"        # For MAE