# Please check the parameters, and adjust them according to your circumstance

# Project name
PROJECT: test

# ================== Control of the workflow ==================

# Provide with these files in order to proceed with the workflow:
Sample_names:  ../config/Sample_names.csv
Experimental_design:  ../config/Experimental_design.csv
Experimental_groups:  ../config/Experimental_groups.csv
Pseudogenome_codes:  ../config/Pseudogenome_codes.csv # after you choose the samples from where you will make the pseudogenomes
GeneID_to_Genebank:  ../config/GeneID_to_Genebank.csv
GO_dict:  ../config/Tilapia gene transcript protein GO KEGG uniprot.csv
tb1_colnames:  ../config/tb1_colnames.csv
tb2_colnames:  ../config/tb2_colnames.csv
Tilapia_dict:  ../config/Tilapia gene transcript protein GO KEGG uniprot.csv
fastq_merged: fastq_merged
Samples_MAE: ../config/Samples_MAE.csv

## Resources of the system:
gpu: 1
#jobs_per_gpu: 6


#Pseudogenomes genome:
java_opts: -XX:MinRAMPercentage=80.0 -Xms200G -XX:-UseConcMarkSweepGC -XX:ParallelGCThreads=2 -XX:+UseTLAB
threads_pseudo: 1
mem_mb_pseudo: 200000


#Combine pseudogenomes (combine_gvcfs_pseudo.smk)
java_opts_combine: -XX:MinRAMPercentage=80.0 -Xms350G -XX:-UseConcMarkSweepGC -XX:ParallelGCThreads=2 -XX:+UseTLAB
threads_combine: 2
mem_mb_combine: 400000

#Reference genome:
java_opts_ref: -XX:MinRAMPercentage=80.0 -Xms800G -XX:-UseConcMarkSweepGC -XX:ParallelGCThreads=8 -XX:+UseTLAB
threads: 4
mem_mb: 800000

# Path to workflow with relation to snakefile. Can vary depending on your HPC configuration
path: /home/ARO.local/aurorac/Projects/Project3/workflow/

results:
  o1:  results/SNPs_function.csv
  o2:  results/SNP_dictionary.csv
  o3:  results/Treatment_SNPs_sig_all_for_Venn.csv
  o4:  results/Summary_of_polymorphisms.csv
  o5:  results/Intronic_SNPs_caryotype.csv

results_mae:
  o1:  results/SNPs_function_mae.csv
  o2:  results/SNP_dictionary_mae.csv
  o3:  results/Treatment_SNPs_sig_all_for_Venn_mae.csv
  o4:  results/Summary_of_polymorphisms_mae.csv
  o5:  results/Intronic_SNPs_caryotype_mae.csv

ref:
  # ensembl species name
  species: Nile tilapia
  # ensembl release
  release: GCF_001858045.2
  # genome build
  build: NMBU
  # file name
  genome:  ../genome/Tilapia_header_GCF_001858045.2.fa
  annotation:  ../genome/Tilapia_GCF_001858045.2_annotation.gff3
  gtf:  ../genome/Tilapia_GCF_001858045.2_annotation.gtf
  SAindex:  ../genome/SAindex
  read_length: 148 # Read length - 1



filtering:
  # Set to true in order to apply machine learning based recalibration of
  # quality scores instead of hard filtering.
  vqsr: false
  hard:
    # hard filtering as outlined in GATK docs
    # (https://gatkforums.broadinstitute.org/gatk/discussion/2806/howto-apply-hard-filters-to-a-call-set)
    snvs:
      "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
    indels:
      "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0"

processing:
  remove-duplicates: true
  # Uncomment and point to a bed file with, e.g., captured regions if necessary,
  # see https://gatkforums.broadinstitute.org/gatk/discussion/4133/when-should-i-use-l-to-pass-in-a-list-of-intervals.
  # restrict-regions: captured_regions.bed
  # If regions are restricted, uncomment this to enlarge them by the given value in order to include
  # flanking areas.
  # region-padding: 100

params:
  star:
    read_length: 148 #read lenght -1
  gatk:
    HaplotypeCaller: ""
    BaseRecalibrator: ""
    GenotypeGVCFs: ""
    VariantRecalibrator: ""
  picard:
    MarkDuplicates: "REMOVE_DUPLICATES=true"
  trimmomatic:
    pe:
      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
        - "ILLUMINACLIP:./resources/TruSeq3-PE-2.fa:2:30:10:2:keepBothReads "
        - "LEADING:3 "
        - "TRAILING:3 "
        #- "SLIDINGWINDOW:4:15 "
        - "MINLEN:36 "

    se:
      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
        - "LEADING:3 "
        - "TRAILING:3 "
        #- "SLIDINGWINDOW:4:15 "
        - "MINLEN:36 "
  vep:
    plugins:
      # Add any plugin from https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html
      # Plugin args can be passed as well, e.g. "LoFtool,path/to/custom/scores.txt".
      - LoFtool
    # extra command line arguments (e.g. --sift, see docs)
    extra: ""
